/**
 * Codex CLI backend. One `codex exec` child process per mention.
 *
 * Chosen on hosts that already run Codex for their real work, so the mention
 * responder draws on the same ChatGPT subscription instead of a second
 * provider. Everything below was verified against codex-cli 0.151 on macOS.
 *
 * ## Where the policy goes
 *
 * Same answer as the Hermes backend, for the same reason: the policy must not
 * share a layer with the mention text, which is untrusted input. Codex
 * auto-injects the `AGENTS.md` of its working directory, so the policy is
 * written there — into a directory this backend owns (`TSSA_CODEX_WORKDIR`),
 * rewritten on every run because it is generated at runtime.
 *
 * The directory is deliberately not a git repository: Codex also reads the
 * `AGENTS.md` files between the repository root and the working directory,
 * and outside a repository there are none to pick up by accident. That is why
 * `--skip-git-repo-check` is always passed.
 *
 * ## Sessions
 *
 * `codex exec --json` prints `{"type":"thread.started","thread_id":...}` as
 * its first event; that id is the session. `codex exec resume <id> <prompt>`
 * continues it and reports the same id.
 *
 * Unlike Hermes, resuming an id Codex no longer has FAILS rather than quietly
 * starting over: exit 1, nothing on stdout, and `no rollout found` on stderr.
 * That is the one failure reported as `sessionUnusable`. Every other failure
 * leaves the stored session alone — including the other ways a resume can
 * fail. `already has an active writer` in particular means an earlier run is
 * still alive on that thread: starting fresh there would let both post.
 *
 * ## What counts as "established"
 *
 * The run is established once `thread.started` was printed: from there on the
 * agent may have run a tool and posted its comment. Before that event nothing
 * has reached the model, so the run cannot have posted anything.
 *
 * ## What counts as "finished"
 *
 * Only a `turn.completed` event. Exit 0 is not enough: a fatal stream error
 * ends the process normally with a top-level `error` event and no turn
 * outcome, and treating that as done would mark an unanswered mention handled.
 * The `error` event alone is not treated as failure either — Codex also emits
 * it for a dropped connection it then recovers from.
 *
 * SECURITY: `codex exec` never asks for approval, so the sandbox is the only
 * thing between a prompt injection and the host. The default
 * (`workspace-write`) confines writes to the run directory and the temporary
 * directories (`/tmp`, `$TMPDIR`) while leaving the network open — the responder needs it for the `taskshoot` CLI. It does NOT
 * restrict reads: anything the daemon's user can read, the agent can read and
 * post. `danger-full-access` removes the sandbox altogether. See the README
 * before deploying this anywhere.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { config } from "../config.js";
import { isShuttingDown } from "../shutdown.js";
import { preflightBinary, runChild, type ChildError } from "./child-process.js";
import { runError, type AgentRunResult, type RunOptions } from "./types.js";

const AGENTS_FILE_HEADER = `<!-- Generated by taskshoot-socket-agent on every run. Do not edit;
     edits are overwritten. This directory belongs to the daemon. -->`;

async function prepareWorkdir(systemPromptAppend: string): Promise<string> {
  const dir = config.codexWorkdir;
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "AGENTS.md"), `${AGENTS_FILE_HEADER}\n\n${systemPromptAppend}\n`);
  return dir;
}

function sandboxArgs(): string[] {
  if (config.codexSandbox === "danger-full-access") {
    return ["--dangerously-bypass-approvals-and-sandbox"];
  }
  return [
    "--sandbox",
    "workspace-write",
    // workspace-write blocks the network unless asked, and without it the
    // agent cannot run the `taskshoot` CLI — it could read the mention but
    // never answer it.
    "-c",
    "sandbox_workspace_write.network_access=true",
    // The host's ~/.codex/config.toml may list extra writable roots for its
    // own interactive use. They would be inherited here and widen what a
    // prompt injection can modify, so they are cleared.
    "-c",
    "sandbox_workspace_write.writable_roots=[]",
  ];
}

interface ParsedEvents {
  threadId: string;
  lastMessage: string;
  turnCompleted: boolean;
  /** The most recent `turn.failed` or top-level `error` message, for the log. */
  lastError: string;
}

/**
 * Reads the JSON Lines Codex printed. Lines that are not JSON are skipped
 * rather than treated as fatal: the stream is the run's only record of the
 * session id, and losing it over one stray line would cost the conversation.
 */
function parseEvents(stdout: string): ParsedEvents {
  const parsed: ParsedEvents = { threadId: "", lastMessage: "", turnCompleted: false, lastError: "" };
  for (const line of stdout.split("\n")) {
    if (!line.startsWith("{")) continue;
    let event: {
      type?: string;
      thread_id?: string;
      item?: { type?: string; text?: string };
      error?: { message?: string };
      message?: string;
    };
    try {
      event = JSON.parse(line);
    } catch {
      continue;
    }
    if (event.type === "thread.started" && event.thread_id) {
      parsed.threadId = event.thread_id;
    } else if (event.type === "item.completed" && event.item?.type === "agent_message") {
      parsed.lastMessage = event.item.text ?? "";
    } else if (event.type === "turn.completed") {
      parsed.turnCompleted = true;
    } else if (event.type === "turn.failed") {
      parsed.turnCompleted = false;
      parsed.lastError = event.error?.message ?? "(no message)";
    } else if (event.type === "error") {
      parsed.lastError = event.message ?? "(no message)";
    }
  }
  return parsed;
}

export async function preflightCodex(): Promise<void> {
  await preflightBinary(config.codexBin, "codex", "TSSA_CODEX_BIN", "Install the Codex CLI");
}

export async function runCodex(prompt: string, options: RunOptions): Promise<AgentRunResult> {
  // Refuse rather than start something that would be killed mid-reply. The
  // mention stays unread and the next daemon answers it once.
  if (isShuttingDown()) throw runError(new Error("daemon is shutting down"), false);
  const cwd = await prepareWorkdir(options.systemPromptAppend);

  // Global options go before `resume`: `codex exec [OPTIONS] resume <id> <prompt>`.
  // The prompt goes through argv, not a shell, so its newlines and quotes need
  // no escaping.
  const args = [
    "exec",
    "--json",
    "--skip-git-repo-check",
    ...sandboxArgs(),
    ...(config.codexModel ? ["--model", config.codexModel] : []),
    ...(options.resumeSessionId ? ["resume", options.resumeSessionId] : []),
    prompt,
  ];

  let stdout: string;
  try {
    ({ stdout } = await runChild(config.codexBin, args, cwd, "codex"));
  } catch (error) {
    const failed = error as ChildError;
    const { threadId } = parseEvents(failed.stdout ?? "");
    const sessionGone =
      options.resumeSessionId !== undefined &&
      threadId === "" &&
      /no rollout found/.test(failed.stderr ?? "");
    // A run that never started its thread keeps the stored session: nothing
    // ran, so the conversation the daemon holds is still the right one.
    throw runError(error, threadId !== "", threadId || undefined, sessionGone);
  }

  const { threadId, lastMessage, turnCompleted, lastError } = parseEvents(stdout);
  if (!turnCompleted) {
    throw runError(
      new Error(`codex ended without completing its turn: ${lastError || "(no error event)"}`),
      threadId !== "",
      threadId || undefined,
    );
  }
  if (!threadId) {
    // No id means the next mention cannot resume this conversation.
    throw runError(new Error("codex printed no thread.started event"), false);
  }
  return { result: lastMessage.trim(), sessionId: threadId };
}
