/**
 * Hermes Agent backend. One `hermes -z` child process per mention.
 *
 * Chosen on hosts whose main job is browser / desktop work rather than coding:
 * Hermes carries browser, web and computer_use toolsets, and is often already
 * resident there as a chat gateway, so the host needs only one agent runtime.
 *
 * ## Where the policy goes
 *
 * Hermes has no "append to the system prompt" flag. Putting the policy in the
 * user prompt instead would place it in the same layer as the mention text —
 * which is untrusted input — so it is written to `AGENTS.md` in the run
 * directory instead: Hermes auto-injects the CWD's `AGENTS.md` (verified on
 * macOS with Hermes 0.18.x).
 *
 * That is also why this backend does NOT run in `TSSA_AGENT_CWD`: it must own
 * the `AGENTS.md` of its working directory, and on a Hermes host that file is
 * very likely already taken by another agent's persona. It uses a directory of
 * its own (`TSSA_HERMES_WORKDIR`) and rewrites the file on every run, because
 * the policy is generated at runtime (bot display name, CLI binary name).
 *
 * ## Sessions
 *
 * `hermes -c <name>` resumes the session with that name and starts a fresh one
 * when the name is unknown — it does NOT fall back to "most recent" (verified:
 * an unknown name did not inherit context from a session created seconds
 * earlier). So this backend invents a name per conversation and returns it as
 * the session id; the daemon persists it per task and hands it back to resume.
 * Nothing has to look up ids in the session store, which matters because other
 * `hermes` processes (a cron loop, a chat gateway) may run concurrently on the
 * same host and would race a "newest session" lookup.
 *
 * ## Process lifecycle
 *
 * Shared with every backend that runs its agent as a child process; see
 * `./child-process.ts`.
 *
 * SECURITY: `--yolo` runs every tool without confirmation — unavoidable with
 * no human at the prompt. Hermes has no deny-list equivalent to Claude Code's
 * settings, so on this backend the policy is guidance only and host isolation
 * is the sole enforcement. See the README before deploying this anywhere.
 */
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { config } from "../config.js";
import { isShuttingDown } from "../shutdown.js";
import { preflightBinary, runChild, type ChildError } from "./child-process.js";
import { runError, type AgentRunResult, type RunOptions } from "./types.js";

const AGENTS_FILE_HEADER = `<!-- Generated by taskshoot-socket-agent on every run. Do not edit;
     edits are overwritten. This directory belongs to the daemon. -->`;

/**
 * Clarification for this backend only, inserted by `buildSystemPromptAppend`
 * between the shared policy and the site policy.
 *
 * The shared "When NOT to reply" section keys off whether the mention asks for
 * something. A plain greeting does not, so read literally it falls under
 * NO_REPLY — and Hermes reads it literally, staying silent where the Claude
 * backend answers. Being greeted and ignored reads as broken.
 *
 * The shared policy is deliberately left alone: it produces the intended
 * behaviour on the other backend, and rewording it would change every host.
 * The clarification is scoped to the runtime that needs it.
 */
export const HERMES_REPLY_NOTE = `## Replying to short messages

Whether to reply is decided by **who the mention is addressed to**, not by
whether it asks for something. A greeting, a thank-you or a remark written to
you gets a short answer in kind. Say something rather than nothing.

A mention that is not addressed to you at all is the usual reason to stay
silent: your name used as a label rather than an address — an ability note in a
task description, a third-person reference to you, your name inside quoted
text. Nobody is waiting on those.

This does not replace the other reasons for NO_REPLY above. In particular, a
mention you have **already answered** still gets silence: the same
notification can reach you twice, so read the thread first and, if your reply
is already there, post nothing rather than saying it again.`;

// Nothing here ever sets `sessionUnusable`: `hermes -c <name>` starts a fresh
// session when the name is unknown rather than failing, so a resume cannot
// come back as "that conversation is gone". A failure means the run did not
// happen — the stored session is still good and must not be replaced.

/** Hermes resolves \`-c\` against session titles, so the name has to be stable
 * and unlikely to collide with sessions created by anything else on the host. */
function newSessionName(): string {
  return `tssa-${randomUUID()}`;
}

async function prepareWorkdir(systemPromptAppend: string): Promise<string> {
  const dir = config.hermesWorkdir;
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "AGENTS.md"), `${AGENTS_FILE_HEADER}\n\n${systemPromptAppend}\n`);
  return dir;
}

export async function preflightHermes(): Promise<void> {
  await preflightBinary(config.hermesBin, "hermes", "TSSA_HERMES_BIN", "Install the Hermes CLI");
}

export async function runHermes(prompt: string, options: RunOptions): Promise<AgentRunResult> {
  // Refuse rather than start something that would be killed mid-reply. The
  // mention stays unread and the next daemon answers it once.
  if (isShuttingDown()) throw runError(new Error("daemon is shutting down"), false);
  const cwd = await prepareWorkdir(options.systemPromptAppend);
  const sessionId = options.resumeSessionId ?? newSessionName();

  // -c names the session (resuming it when it already exists), --yolo skips
  // tool confirmations. The prompt goes through argv, not a shell, so its
  // newlines and quotes need no escaping.
  const args = ["-z", prompt, "--yolo", "-c", sessionId];

  try {
    const { stdout } = await runChild(config.hermesBin, args, cwd, "hermes");
    return { result: stdout.trim(), sessionId };
  } catch (error) {
    // Anything past a successful spawn counts as established, because the run
    // may already have posted its comment via a tool call. Final output is NOT
    // a usable proxy: `hermes -z` prints its answer only at the end, so a run
    // that commented and then timed out emits nothing — and the daemon would
    // read "not established" as "the stored session was unusable", retry the
    // mention fresh, and reply twice.
    //
    // There is also nothing to recover by retrying: an unknown `-c` name makes
    // Hermes start a new session instead of failing, so this backend has no
    // "the resume itself failed" mode for that path to fix.
    const spawned = (error as ChildError).spawned === true;
    throw runError(error, spawned, spawned ? sessionId : undefined);
  }
}
