/**
 * Hermes Agent backend. One `hermes -z` child process per mention.
 *
 * Chosen on hosts whose main job is browser / desktop work rather than coding:
 * Hermes carries browser, web and computer_use toolsets, and is often already
 * resident there as a chat gateway, so the host needs only one agent runtime.
 *
 * ## Where the policy goes
 *
 * Hermes has no "append to the system prompt" flag. Putting the policy in the
 * user prompt instead would place it in the same layer as the mention text —
 * which is untrusted input — so it is written to `AGENTS.md` in the run
 * directory instead: Hermes auto-injects the CWD's `AGENTS.md` (verified on
 * macOS with Hermes 0.18.x).
 *
 * That is also why this backend does NOT run in `TSSA_AGENT_CWD`: it must own
 * the `AGENTS.md` of its working directory, and on a Hermes host that file is
 * very likely already taken by another agent's persona. It uses a directory of
 * its own (`TSSA_HERMES_WORKDIR`) and rewrites the file on every run, because
 * the policy is generated at runtime (bot display name, CLI binary name).
 *
 * ## Sessions
 *
 * `hermes -c <name>` resumes the session with that name and starts a fresh one
 * when the name is unknown — it does NOT fall back to "most recent" (verified:
 * an unknown name did not inherit context from a session created seconds
 * earlier). So this backend invents a name per conversation and returns it as
 * the session id; the daemon persists it per task and hands it back to resume.
 * Nothing has to look up ids in the session store, which matters because other
 * `hermes` processes (a cron loop, a chat gateway) may run concurrently on the
 * same host and would race a "newest session" lookup.
 *
 * ## Process lifecycle
 *
 * Hermes is a child process that starts children of its own (browser, shell),
 * so every ending has to account for the whole group. The rules, in one place
 * because fixing them one case at a time is how they got missed:
 *
 * | Ending | Settle | Group |
 * |---|---|---|
 * | spawn failed | reject, retryable | nothing exists |
 * | exit 0 | resolve | terminate — tools may still be running |
 * | exit non-zero / signal | reject | terminate |
 * | timeout | reject | terminate (SIGTERM, then SIGKILL after a grace) |
 * | daemon shutting down | — | terminate every live run, then exit |
 *
 * Two asymmetries are deliberate. `exit` (not `close`) settles the run,
 * because a descendant holding the inherited pipes keeps `close` from ever
 * firing — which would leave the daemon's serial queue stuck. And the SIGKILL
 * escalation is never cancelled: the run settling means Hermes is gone, which
 * is exactly when a tool that ignored SIGTERM would be left behind for good.
 *
 * SECURITY: `--yolo` runs every tool without confirmation — unavoidable with
 * no human at the prompt. Hermes has no deny-list equivalent to Claude Code's
 * settings, so on this backend the policy is guidance only and host isolation
 * is the sole enforcement. See the README before deploying this anywhere.
 */
import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { config } from "../config.js";
import { isShuttingDown, onShutdown } from "../shutdown.js";
import { runError, type AgentRunResult, type RunOptions } from "./types.js";

const AGENTS_FILE_HEADER = `<!-- Generated by taskshoot-socket-agent on every run. Do not edit;
     edits are overwritten. This directory belongs to the daemon. -->`;

// Nothing here ever sets `sessionUnusable`: `hermes -c <name>` starts a fresh
// session when the name is unknown rather than failing, so a resume cannot
// come back as "that conversation is gone". A failure means the run did not
// happen — the stored session is still good and must not be replaced.

/** Hermes resolves \`-c\` against session titles, so the name has to be stable
 * and unlikely to collide with sessions created by anything else on the host. */
function newSessionName(): string {
  return `tssa-${randomUUID()}`;
}

/** SIGTERM to SIGKILL grace for the run's process group. */
const KILL_GRACE_MS = 10_000;
/** How long to wait for `close` after `exit` before settling anyway. */
const CLOSE_FALLBACK_MS = 2_000;

/**
 * Signals the run's whole process group, not just Hermes itself.
 *
 * The child is spawned detached, so it leads its own group and the negative
 * pid reaches its tool subprocesses too. Failures are ignored on purpose: the
 * group is already gone in the common case (the process exited between the
 * timeout firing and this call), and there is nothing to recover either way.
 */
function killTree(child: { pid?: number }, signal: NodeJS.Signals): void {
  if (child.pid === undefined) return;
  try {
    process.kill(-child.pid, signal);
  } catch {
    // The group is gone. Deliberately no fallback to the positive pid: the
    // escalation fires seconds later, by which time that number may belong to
    // an unrelated process — signalling it would kill a stranger.
  }
}

/** Runs whose process group may still exist. Used to clean up on shutdown. */
const liveRuns = new Set<{ pid?: number }>();
let cleanupRegistered = false;

/**
 * Ends every running group when the daemon stops.
 *
 * `detached` puts each run outside the daemon's own process group, so neither
 * supervisor's `stopasgroup` nor launchd reaches it: without this a restart
 * would leave the old run free to post its reply — never recorded in the
 * ledger, because the daemon that would record it is gone — while the new
 * daemon retries the same mention and replies again.
 */
function registerCleanup(): void {
  if (cleanupRegistered) return;
  cleanupRegistered = true;
  onShutdown((phase) => {
    // SIGTERM first so a run can wind down, then SIGKILL from the force phase
    // — which runs immediately before the process exits. The per-run
    // escalation cannot cover this: it is armed only when a run finishes, and
    // its grace is longer than the daemon's, so a group that ignored SIGTERM
    // would outlive the daemon and post a late comment while the restarted
    // one retries the mention.
    for (const child of liveRuns) killTree(child, phase === "stop" ? "SIGTERM" : "SIGKILL");
  });
}

async function prepareWorkdir(systemPromptAppend: string): Promise<string> {
  const dir = config.hermesWorkdir;
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "AGENTS.md"), `${AGENTS_FILE_HEADER}\n\n${systemPromptAppend}\n`);
  return dir;
}

/**
 * Fails fast when the configured `hermes` is not runnable.
 *
 * Without this the daemon starts perfectly, then every mention dies at spawn
 * and stays unread while the backstop retries it — the misconfiguration is
 * only visible in the logs of runs that already looked like failures.
 */
export async function preflightHermes(): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(config.hermesBin, ["--version"], { stdio: "ignore" });
    child.on("error", (error) =>
      reject(
        new Error(
          `TSSA_AGENT_BACKEND=hermes but \`${config.hermesBin} --version\` could not run ` +
            `(${error.message}). Install the Hermes CLI or set TSSA_HERMES_BIN.`,
        ),
      ),
    );
    child.on("close", (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`\`${config.hermesBin} --version\` exited with ${code}`)),
    );
  });
}

export async function runHermes(prompt: string, options: RunOptions): Promise<AgentRunResult> {
  registerCleanup();
  // Refuse rather than start something that would be killed mid-reply. The
  // mention stays unread and the next daemon answers it once.
  if (isShuttingDown()) throw runError(new Error("daemon is shutting down"), false);
  const cwd = await prepareWorkdir(options.systemPromptAppend);
  const sessionId = options.resumeSessionId ?? newSessionName();

  // -c names the session (resuming it when it already exists), --yolo skips
  // tool confirmations. The prompt goes through argv, not a shell, so its
  // newlines and quotes need no escaping.
  const args = ["-z", prompt, "--yolo", "-c", sessionId];

  // Re-checked after preparing the workdir: a signal can arrive during that
  // await, and spawning here is what posts a reply the ledger never records.
  if (isShuttingDown()) throw runError(new Error("daemon is shutting down"), false);

  return await new Promise<AgentRunResult>((resolve, reject) => {
    // detached: the run gets its own process group. Hermes spawns tool
    // subprocesses (browser, shell), and killing only the parent would leave
    // them running --yolo past the hard timeout — free to finish a browser
    // action or post a late comment while the backstop retries the mention.
    const child = spawn(config.hermesBin, args, {
      cwd,
      stdio: ["ignore", "pipe", "pipe"],
      detached: true,
    });
    liveRuns.add(child);

    let stdout = "";
    let stderr = "";
    let timedOut = false;
    let spawned = false;
    let settled = false;
    let closeFallback: NodeJS.Timeout | undefined;

    /** `exit` + `close` + the fallback can all fire; only the first one wins. */
    const settle = (action: () => void) => {
      if (settled) return;
      settled = true;
      action();
    };

    const timer = setTimeout(
      () => {
        timedOut = true;
        terminateGroup();
      },
      config.agentTimeoutMinutes * 60 * 1000,
    );

    /**
     * Ends the run's whole process group.
     *
     * Called for every abnormal end, not just the timeout: Hermes exiting
     * non-zero says nothing about the tool subprocesses it started, and as the
     * group leader it takes none of them with it. A survivor is an unattended
     * `--yolo` process still free to act — and to post a late comment while
     * the backstop retries the mention.
     *
     * The SIGKILL escalation is deliberately NOT cancelled when the run
     * settles: settling means Hermes is gone, which is exactly when a
     * subprocess that ignored SIGTERM would otherwise be left alive for good.
     * It is unref'd so it never keeps a process alive on its own, and it is a
     * no-op once the group is gone.
     */
    const terminateGroup = () => {
      killTree(child, "SIGTERM");
      if (!graceTimer) {
        graceTimer = setTimeout(() => {
          killTree(child, "SIGKILL");
          // Only now is the group certainly gone. Until then it stays in
          // liveRuns: a descendant that ignored SIGTERM is still out there,
          // and if the daemon is told to stop during this window, the force
          // phase has to be able to find it — this timer is unref'd and
          // outlasts the daemon's own grace, so it cannot be relied on.
          liveRuns.delete(child);
        }, KILL_GRACE_MS);
        graceTimer.unref();
      }
    };
    let graceTimer: NodeJS.Timeout | undefined;

    const clearTimers = () => {
      clearTimeout(timer);
      if (closeFallback) clearTimeout(closeFallback);
    };

    child.stdout.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });

    // Anything past a successful spawn counts as established, because the run
    // may already have posted its comment via a tool call. Final output is NOT
    // a usable proxy: `hermes -z` prints its answer only at the end, so a run
    // that commented and then timed out emits nothing — and the daemon would
    // read "not established" as "the stored session was unusable", retry the
    // mention fresh, and reply twice.
    //
    // There is also nothing to recover by retrying: an unknown `-c` name makes
    // Hermes start a new session instead of failing, so this backend has no
    // "the resume itself failed" mode for that path to fix.
    child.on("spawn", () => {
      spawned = true;
    });

    child.on("error", (error) => {
      clearTimers();
      // Nothing was started when the spawn itself failed; otherwise the group
      // may exist and is cleaned up on the normal schedule.
      if (spawned) terminateGroup();
      else liveRuns.delete(child);
      settle(() => reject(runError(error, spawned, spawned ? sessionId : undefined)));
    });

    // `close` waits for the pipes, and a surviving grandchild can hold them
    // open after Hermes itself is gone — which would leave this promise (and
    // the daemon's serial queue behind it) pending forever. `exit` is the
    // process actually ending, so it arms a short fallback that settles the
    // run with whatever output arrived.
    child.on("exit", (code, signal) => {
      closeFallback = setTimeout(() => finish(code, signal), CLOSE_FALLBACK_MS);
    });

    child.on("close", (code, signal) => finish(code, signal));

    function finish(code: number | null, signal: NodeJS.Signals | null) {
      clearTimers();
      // Unconditional, including a clean exit: Hermes finishing says nothing
      // about the tools it started, and a background browser or shell that
      // inherited the pipes would otherwise keep acting unattended after the
      // mention is marked handled.
      terminateGroup();
      if (timedOut) {
        settle(() =>
          reject(
            runError(
              new Error(
                `hermes run exceeded ${config.agentTimeoutMinutes} minutes and was killed`,
              ),
              spawned,
              sessionId,
            ),
          ),
        );
        return;
      }
      if (code !== 0 || signal) {
        settle(() =>
          reject(
            runError(
              new Error(
                `hermes exited with ${signal ? `signal ${signal}` : `code ${code}`}: ` +
                  `${stderr.trim().slice(-500) || "(no stderr)"}`,
              ),
              spawned,
              sessionId,
            ),
          ),
        );
        return;
      }
      settle(() => resolve({ result: stdout.trim(), sessionId }));
    }
  });
}
