/**
 * Hermes Agent backend. One `hermes -z` child process per mention.
 *
 * Chosen on hosts whose main job is browser / desktop work rather than coding:
 * Hermes carries browser, web and computer_use toolsets, and is often already
 * resident there as a chat gateway, so the host needs only one agent runtime.
 *
 * ## Where the policy goes
 *
 * Hermes has no "append to the system prompt" flag. Putting the policy in the
 * user prompt instead would place it in the same layer as the mention text —
 * which is untrusted input — so it is written to `AGENTS.md` in the run
 * directory instead: Hermes auto-injects the CWD's `AGENTS.md` (verified on
 * macOS with Hermes 0.18.x).
 *
 * That is also why this backend does NOT run in `TSSA_AGENT_CWD`: it must own
 * the `AGENTS.md` of its working directory, and on a Hermes host that file is
 * very likely already taken by another agent's persona. It uses a directory of
 * its own (`TSSA_HERMES_WORKDIR`) and rewrites the file on every run, because
 * the policy is generated at runtime (bot display name, CLI binary name).
 *
 * ## Sessions
 *
 * `hermes -c <name>` resumes the session with that name and starts a fresh one
 * when the name is unknown — it does NOT fall back to "most recent" (verified:
 * an unknown name did not inherit context from a session created seconds
 * earlier). So this backend invents a name per conversation and returns it as
 * the session id; the daemon persists it per task and hands it back to resume.
 * Nothing has to look up ids in the session store, which matters because other
 * `hermes` processes (a cron loop, a chat gateway) may run concurrently on the
 * same host and would race a "newest session" lookup.
 *
 * SECURITY: `--yolo` runs every tool without confirmation — unavoidable with
 * no human at the prompt. Hermes has no deny-list equivalent to Claude Code's
 * settings, so on this backend the policy is guidance only and host isolation
 * is the sole enforcement. See the README before deploying this anywhere.
 */
import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { config } from "../config.js";
import { runError, type AgentRunResult, type RunOptions } from "./types.js";

const AGENTS_FILE_HEADER = `<!-- Generated by taskshoot-socket-agent on every run. Do not edit;
     edits are overwritten. This directory belongs to the daemon. -->`;

/** Hermes resolves \`-c\` against session titles, so the name has to be stable
 * and unlikely to collide with sessions created by anything else on the host. */
function newSessionName(): string {
  return `tssa-${randomUUID()}`;
}

async function prepareWorkdir(systemPromptAppend: string): Promise<string> {
  const dir = config.hermesWorkdir;
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "AGENTS.md"), `${AGENTS_FILE_HEADER}\n\n${systemPromptAppend}\n`);
  return dir;
}

export async function runHermes(prompt: string, options: RunOptions): Promise<AgentRunResult> {
  const cwd = await prepareWorkdir(options.systemPromptAppend);
  const sessionId = options.resumeSessionId ?? newSessionName();

  // -c names the session (resuming it when it already exists), --yolo skips
  // tool confirmations. The prompt goes through argv, not a shell, so its
  // newlines and quotes need no escaping.
  const args = ["-z", prompt, "--yolo", "-c", sessionId];

  return await new Promise<AgentRunResult>((resolve, reject) => {
    const child = spawn(config.hermesBin, args, {
      cwd,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let timedOut = false;
    let spawned = false;

    const timer = setTimeout(
      () => {
        timedOut = true;
        child.kill("SIGKILL");
      },
      config.agentTimeoutMinutes * 60 * 1000,
    );

    child.stdout.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });

    // Anything past a successful spawn counts as established, because the run
    // may already have posted its comment via a tool call. Final output is NOT
    // a usable proxy: `hermes -z` prints its answer only at the end, so a run
    // that commented and then timed out emits nothing — and the daemon would
    // read "not established" as "the stored session was unusable", retry the
    // mention fresh, and reply twice.
    //
    // There is also nothing to recover by retrying: an unknown `-c` name makes
    // Hermes start a new session instead of failing, so this backend has no
    // "the resume itself failed" mode for that path to fix.
    child.on("spawn", () => {
      spawned = true;
    });

    child.on("error", (error) => {
      clearTimeout(timer);
      reject(runError(error, spawned));
    });

    child.on("close", (code, signal) => {
      clearTimeout(timer);
      if (timedOut) {
        reject(
          runError(
            new Error(`hermes run exceeded ${config.agentTimeoutMinutes} minutes and was killed`),
            spawned,
          ),
        );
        return;
      }
      if (code !== 0) {
        reject(
          runError(
            new Error(
              `hermes exited with ${signal ? `signal ${signal}` : `code ${code}`}: ` +
                `${stderr.trim().slice(-500) || "(no stderr)"}`,
            ),
            spawned,
          ),
        );
        return;
      }
      resolve({ result: stdout.trim(), sessionId });
    });
  });
}
